# Generated by Django 2.2.13 on 2020-07-01 00:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vestlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupmessage',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
