# Generated by Django 2.2.13 on 2020-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestlus', '0002_auto_20200701_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='channels/photos/', verbose_name='photo'),
        ),
    ]
